name: latest
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout tag
        uses: actions/checkout@v3
      - name: setup qemu
        uses: docker/setup-qemu-action@v3
      - name: setup buildx
        uses: docker/setup-buildx-action@v3
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        run: |
          version="latest"
          target="protoc"
          docker buildx build \
            --target "${target}" \
            --tag "chaseisabelle/${target}:${version}" \
            --platform=linux/amd64,linux/arm64 \
            --push \
            .
          target="sqlboiler"
          docker buildx build \
            --target "${target}" \
            --tag "chaseisabelle/${target}:${version}" \
            --platform=linux/amd64,linux/arm64 \
            --push \
            .
          target="oapi"
          docker buildx build \
            --target "${target}" \
            --tag "chaseisabelle/${target}:${version}" \
            --platform=linux/amd64,linux/arm64 \
            --push \
            .
          target="swagger"
          docker buildx build \
            --target "${target}" \
            --tag "chaseisabelle/${target}:${version}" \
            --platform=linux/amd64,linux/arm64 \
            --push \
            .