name: release
on:
  push:
    branches:
      - release/*-* # @todo remove this after testing
    tags:
      - release/*-*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          target=$(echo "$GITHUB_REF_NAME" | grep -oP "(?<=release\/)([a-zA-Z0-9]+)-[0-9]+(\.[0-9]+)?(\.[0-9]+)?")
          version=$(echo "$GITHUB_REF_NAME" | grep -oP "(?<=release\/$target-)[0-9]+\.[0-9]+(\.[0-9]+)?")
          echo $target
          echo $version