name: release
on:
  push:
    branches:
      - release/*-* # @todo remove this after testing
    tags:
      - release/*-*
jobs:
  reelase:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          version=$(echo "$GITHUB_REF_NAME" | grep -oP "(?<=protoc-)[0-9]+\.[0-9]+\.[0-9]+")
          echo $version