name: release
on:
  push:
    tags:
      - release/*-*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout tag
        uses: actions/checkout@v3
      - name: setup qemu
        uses: docker/setup-qemu-action@v3
      - name: setup buildx
        uses: docker/setup-buildx-action@v3
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: generate target
        run: |
          target=$(make parse-release-target tag="$GITHUB_REF_NAME")
          echo "got target $target from $GITHUB_REF_NAME"
          echo "target=$target" >> $GITHUB_ENV
      - name: generate version
        run: |
          version=$(make parse-release-version tag="$GITHUB_REF_NAME")
          echo "got version $version from $GITHUB_REF_NAME"
          echo "version=$version" >> $GITHUB_ENV
      - name: build and push
        run: |
          make build-and-push target="${target}" version="${version}"