name: release
on:
  push:
    branches:
      - release/*-* # @todo remove this after testing
    tags:
      - release/*-*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          target=$(make target input="$GITHUB_REF_NAME")
          version=$(make version input="$GITHUB_REF_NAME")
          echo releasing "$target-$version" from tag "$GITHUB_REF_NAME"