name: release
on:
  push:
    branches:
      - release/*-* # @todo remove this after testing
    tags:
      - release/*-*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: initialize
        run: |
          target=$(make target input="$GITHUB_REF_NAME")
          version=$(make version input="$GITHUB_REF_NAME")
          echo "target=$target" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_ENV
          echo releasing "$target-$version" from tag "$GITHUB_REF_NAME"
      - name: build
        run: |
          make build target="$target" version="$version"
      - name: push
        run: |
          make push target="$target" version="$version"