name: release
on:
  push:
    branches:
      - release/*-* # @todo remove this after testing
    tags:
      - release/*-*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout tag
        uses: actions/checkout@v3
      - name: setup qemu
        uses: docker/setup-qemu-action@v3
      - name: setup buildx
        uses: docker/setup-buildx-action@v3
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: generate target
        run: |
          target=$(make target input="$GITHUB_REF_NAME")
          echo "target=$target" >> $GITHUB_ENV
      - name: generate version
        run: |
          version=$(make version input="$GITHUB_REF_NAME")
          echo "version=$version" >> $GITHUB_ENV
      - name: build and push
        run: |
          make build target="$target" version="$version"
          make push target="$target" version="$version"
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: chaseisabelle/$target:$version